server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  minio:
    endpoint: 192.168.3.125:9000
    accessKey: LH1I4a83WdghqEmTnZmw
    secretKey: 3xRjjBTJ3ZAcOIvgcDAmkOZQvY8NYAIefNSFTpkK
    secure: true
    token:

